# Workflow configuration for continuous integration

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # Lint and run unit tests
  test-unit:
    runs-on: ubuntu-latest
        
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js v16.13.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install dependencies
        run: yarn install

      - name: Lint files
        run: yarn lint

      - name: Run unit tests
        run: yarn test:unit --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      

